;; Ruby stuff
(require 'ruby-mode)
(require 'ruby-electric)
(defun chneeb-ruby-mode-hook()
  (font-lock-mode t)
  (setq standard-indent 2)
  (set (make-local-variable 'compile-command) (concat "ruby " (buffer-file-name)))
  (local-set-key "\C-c\C-c" 'compile)
  (local-set-key "\C-c\C-d" 'rdebug)
  (ruby-electric-mode t))
(add-hook 'ruby-mode-hook 'chneeb-ruby-mode-hook)
;; Fixing ruby-insert-end
(defun ruby-insert-end () 
  "Insert \"end\" at point and reindent current line." 
  (interactive) 
  (insert "end") 
  (ruby-indent-line t) 
  (end-of-line)) 
(require 'rinari)
;;(require 'rdebug)
